name: music_app
description: A music player application built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  go_router: ^13.2.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^4.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/